import Header from '@/components/shared/Header';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';
import Providers from '@/utils/Providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { CartProvider } from '@/contexts/cart';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'P & P',
    description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} text-sm font-poppin`}>
                <Providers>
                    <CartProvider>
                        <Header />
                        <Navbar />
                        {children}
                        <Footer />
                        <ToastContainer position="bottom-right" theme="dark" autoClose={3000} />
                    </CartProvider>
                </Providers>
            </body>
        </html>
    );
}
